#!/bin/bash


mkdir logs

chmod +x ~/binder/start.redis 
chmod +x ~/binder/start.vscode 

# starting redis in parallel
~/binder/start.redis &

# starting vscode in parallel
~/binder/start.vscode   &


cd ~
echo " " >> .gitignore
echo "resources/local/" >> .gitignore
echo ".local/" >> .gitignore
echo "local-home/" >> .gitignore


# adding my own extensions
mkdir -p ~/.ipython/extensions/
cp       ~/.ipython/extensions/* ~/.ipython/extensions/



# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
