#!/bin/bash


chmod +x ~/binder/start.redis 

# starting redis in parallel
~/binder/start.redis &

# starting vscode in parallel
code-server .  --auth none &



# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"